### ISSUE TITLE
properties with default values

### ISSUE THREAD

**Issue by SingingBush** [free-beer/proper-d#2]
Hi Peter, I've just started to use your lib along with [poodinis](https://github.com/mbierlee/poodinis) and [hibernated](https://github.com/mbierlee/hibernated). I want to use proper-d as a convenient way to keep my db properties out of the source.

It would be handy to be able to specify some defaults in case a property cannot be found. eg:

```
auto dbHost = properties.as!(string)("domain:localhost");
auto dbPort = properties.as!(int)("port:3306");
auto dbUser = properties.as!(string)("username");
auto dbPass = properties.as!(string)("password");
```

or something to that effect.

also, dub complains about using `~master` as a dependency version now as it's deprecated in favour of using a numbered version.

**Comment by free-beer** [comment]
Sorry for the slow response time (time of year and all that). Been a while since I've looked at this but I'll see if I can get some time to look at the points you've raised. Alternatively, if you wish to contribute, I'd happily look over a pull request(s).

**Comment by free-beer** [comment]
Just taking another look at this now. I kinda thought I'd allowed for defaults when I wrote this library (such a long time ago) and from looking at the code it seems I did. If I'm interpreting my own code correctly you do it like this...

    auto dbHost = properties.as!(string)("domain", "localhost");
    auto dbPort = properties.as!(int)("port", 3306);

And so on. Not quite as concise as the version you outlined but achieves the same end result.

**Comment by free-beer** [comment]
Closing this one down as I believe defaults are covered by the existing code base as outlined above. Let me know if you're having issue with this.

**Comment by SingingBush** [comment]
cheers for getting back to me. I should've read the source instead of just looking at the readme.
