### ISSUE TITLE
mismatched module name causes compile error with recent versions of dub

### ISSUE THREAD

**Issue by SingingBush** [free-beer/proper-d#3]
using dub 0.9.24 (or likely any other recent build) adding proper-d as a dependency will cause builds to fail with the following:

```
source/app.d(10,8): Error: module properd is in file 'properd.d' which cannot be read
```

This is to do with the fact that the module is named 'properd' while the name in your `package.json` is 'proper-d'. See a similar problem [here on the rejected software forum](http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1323/).

It may be worth setting proper-d to do builds with [travis-ci](https://travis-ci.org) before deploying another build to the dub repo. The following `.travis.yml` should do the trick:

```
language: d

services:
  - docker

d:
  - dmd
  - gdc
  - ldc

os:
  - linux
  - osx
```

**Comment by free-beer** [comment]
Okay I've renamed the proper-d.d file to just properd.d and I was able to build a simple application against the library. I've also added versioning although, to be honest, I find the dub package manager documentation to be frustrating inadequate so I'm not sure whether I have done everything required and I wasn't able to successful specify a version that worked other than "*" (please feel free to enlighten me if you know better). I'll take a look at enabling Travis when I get time.

**Comment by SingingBush** [comment]
awesome, thanks for the new release. That's helped with [my build](https://travis-ci.org/SingingBush/eloquent/builds/99846232).
